### ISSUE TITLE
Support pseudo tty?

### ISSUE THREAD

**Issue by hongquan** [neundorf/CuteCom#76] opened 2018-07-20 14:22 UTC
I'm writing application which talk with device via serial port. But when in development, I often let my application talk with a virtual serial port (created with `socat`) first. It would be great that CuteCom support virtual serial port, too, to help in developing.

**Comment by cyc1ingsir** [comment] 2018-07-22 13:32
Hi,
this is a duplicate of #44.
Please have a look at the discussion over there about the reasons and possible solutions.
I'd would like to stick as closely as possible to the capabilities of QtSerialPort. Best solution was if QtSerialPort were enabled to discover virtual ports / pseudo tty also.

**Closed by cyc1ingsir** 2018-07-22 13:32 UTC
